name: ride_hail
description: "Ride Hail, Infosys Buggy Booking System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
# routing
  go_router: ^15.1.1
# env
  flutter_dotenv: ^5.2.1
# state management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  get_it: ^8.0.3
  rxdart: ^0.28.0
# notifications
  onesignal_flutter: ^5.3.2
  firebase_core: ^3.13.1
# ui
  toastification:
  flutter_spinkit: ^5.2.1
  dropdown_button2:
  toggle_list: ^0.3.1
  flutter_datetime_picker_plus: ^2.2.0
# maps
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  flutter_polyline_points: ^2.1.0
  location:
  location_geocoder: ^1.0.5
  animated_marker: ^0.1.4
# utility
  uuid: ^4.5.1
  intl: ^0.20.2
  string_validator: ^1.1.0
  path_provider: ^2.1.5
# auth and security
  jwt_decoder: ^2.0.1
  pinput: ^5.0.1
  google_sign_in: ^6.3.0
# code
  equatable: ^2.0.7
  fpdart: ^1.1.1
# image
  image_picker: ^1.1.2
  mime:
# network
  http:
  http_parser:
  socket_io_client: ^3.1.2
  internet_connection_checker_plus: ^2.7.2
# permission
  permission_handler:
# storage
  flutter_secure_storage:

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    [ .env,
      assets/map_themes/dark-theme.json,
      assets/map_themes/light-theme.json,
      assets/images/blue_wave.png,
      assets/images/blue_wave_2x.png,
      assets/images/google-logo-48.png,
      assets/images/buggy-ride.png,
      assets/images/buggy-ride-2x.png,
      assets/images/transport-truck.png,
      assets/images/transport-truck-2x.png,
      assets/images/bot.png,
      assets/images/Infosys_logo_natural.png,
      assets/images/Infosys_logo_natural_2x.png,
      assets/images/icon-location.png,
      assets/images/icon-location-2x.png,
      assets/images/select-from-map-2x.png,
      assets/images/select-from-map.png,
      assets/images/booking-confirmed.png,
      assets/images/booking-confirmed-2x.png,
      assets/images/buggy-marker-icon.png,
      assets/images/buggy-marker-icon-2x.png,
      assets/images/map-pin-2x.png,
      assets/images/map-pin.png,
    ]

